# Service
apiVersion: v1
kind: Service
metadata:
  name: hcm-azure
  namespace: default
  labels:
    app: hcm-azure
spec:
  ports:
    - name: tcp-web
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: hcm-azure
  type: ClusterIP
---
# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hcm-azure
  namespace: default
  labels:
    app: hcm-azure
spec:
  template:
    metadata:
      labels:
        app: hcm-azure
    spec:
      containers:
        - name: hcm-azure
          image: kurts/hcm_azure
      imagePullSecrets:
        - name: regcred
---

